version: 0.2

phases:
  install:
    commands:
      -  # TODO
  pre_build:
    commands:
      -  # TODO
  build:
    commands:
      - |
        docker run --rm -it -v "$(pwd):/local" openapitools/openapi-generator-cli \
          generate -i /local/bridge_and_ivms.json \
          -g typescript-fetch \
          -t /local/typescript/template \
          -o /local/tmp
      - mv ./tmp/models/* ./typescript/src/generated/
      - rm -r ./tmp
      - |
        docker run --rm -it -v "$(pwd):/local" openapitools/openapi-generator-cli \
          generate -i /local/bridge_and_ivms.json \
          -g python \
          -t /local/python/template \
          -o /local/tmp
      - mv ./tmp/openapi_client/models/* ./python/generated/
      - rm -r ./tmp
