/*
Bridge

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ivms101

import (
	"encoding/json"
	"fmt"
)

// NaturalPersonNameTypeCode the model 'NaturalPersonNameTypeCode'
type NaturalPersonNameTypeCode string

// List of NaturalPersonNameTypeCode
const (
	NATURALPERSONNAMETYPECODE_ALIA NaturalPersonNameTypeCode = "ALIA"
	NATURALPERSONNAMETYPECODE_BIRT NaturalPersonNameTypeCode = "BIRT"
	NATURALPERSONNAMETYPECODE_MAID NaturalPersonNameTypeCode = "MAID"
	NATURALPERSONNAMETYPECODE_LEGL NaturalPersonNameTypeCode = "LEGL"
	NATURALPERSONNAMETYPECODE_MISC NaturalPersonNameTypeCode = "MISC"
)

// All allowed values of NaturalPersonNameTypeCode enum
var AllowedNaturalPersonNameTypeCodeEnumValues = []NaturalPersonNameTypeCode{
	"ALIA",
	"BIRT",
	"MAID",
	"LEGL",
	"MISC",
}

func (v *NaturalPersonNameTypeCode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := NaturalPersonNameTypeCode(value)
	for _, existing := range AllowedNaturalPersonNameTypeCodeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid NaturalPersonNameTypeCode", value)
}

// NewNaturalPersonNameTypeCodeFromValue returns a pointer to a valid NaturalPersonNameTypeCode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewNaturalPersonNameTypeCodeFromValue(v string) (*NaturalPersonNameTypeCode, error) {
	ev := NaturalPersonNameTypeCode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for NaturalPersonNameTypeCode: valid values are %v", v, AllowedNaturalPersonNameTypeCodeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v NaturalPersonNameTypeCode) IsValid() bool {
	for _, existing := range AllowedNaturalPersonNameTypeCodeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to NaturalPersonNameTypeCode value
func (v NaturalPersonNameTypeCode) Ptr() *NaturalPersonNameTypeCode {
	return &v
}

type NullableNaturalPersonNameTypeCode struct {
	value *NaturalPersonNameTypeCode
	isSet bool
}

func (v NullableNaturalPersonNameTypeCode) Get() *NaturalPersonNameTypeCode {
	return v.value
}

func (v *NullableNaturalPersonNameTypeCode) Set(val *NaturalPersonNameTypeCode) {
	v.value = val
	v.isSet = true
}

func (v NullableNaturalPersonNameTypeCode) IsSet() bool {
	return v.isSet
}

func (v *NullableNaturalPersonNameTypeCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNaturalPersonNameTypeCode(val *NaturalPersonNameTypeCode) *NullableNaturalPersonNameTypeCode {
	return &NullableNaturalPersonNameTypeCode{value: val, isSet: true}
}

func (v NullableNaturalPersonNameTypeCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNaturalPersonNameTypeCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

