/*
 * Bridge
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ivms101

import (
	"encoding/json"
)

// Beneficiary struct for Beneficiary
type Beneficiary struct {
	BeneficiaryPersons *[]Person `json:"beneficiary_persons,omitempty"`
	AccountNumbers *[]string `json:"account_numbers,omitempty"`
}

// NewBeneficiary instantiates a new Beneficiary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBeneficiary() *Beneficiary {
	this := Beneficiary{}
	return &this
}

// NewBeneficiaryWithDefaults instantiates a new Beneficiary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBeneficiaryWithDefaults() *Beneficiary {
	this := Beneficiary{}
	return &this
}

// GetBeneficiaryPersons returns the BeneficiaryPersons field value if set, zero value otherwise.
func (o *Beneficiary) GetBeneficiaryPersons() []Person {
	if o == nil || o.BeneficiaryPersons == nil {
		var ret []Person
		return ret
	}
	return *o.BeneficiaryPersons
}

// GetBeneficiaryPersonsOk returns a tuple with the BeneficiaryPersons field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Beneficiary) GetBeneficiaryPersonsOk() (*[]Person, bool) {
	if o == nil || o.BeneficiaryPersons == nil {
		return nil, false
	}
	return o.BeneficiaryPersons, true
}

// HasBeneficiaryPersons returns a boolean if a field has been set.
func (o *Beneficiary) HasBeneficiaryPersons() bool {
	if o != nil && o.BeneficiaryPersons != nil {
		return true
	}

	return false
}

// SetBeneficiaryPersons gets a reference to the given []Person and assigns it to the BeneficiaryPersons field.
func (o *Beneficiary) SetBeneficiaryPersons(v []Person) {
	o.BeneficiaryPersons = &v
}

// GetAccountNumbers returns the AccountNumbers field value if set, zero value otherwise.
func (o *Beneficiary) GetAccountNumbers() []string {
	if o == nil || o.AccountNumbers == nil {
		var ret []string
		return ret
	}
	return *o.AccountNumbers
}

// GetAccountNumbersOk returns a tuple with the AccountNumbers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Beneficiary) GetAccountNumbersOk() (*[]string, bool) {
	if o == nil || o.AccountNumbers == nil {
		return nil, false
	}
	return o.AccountNumbers, true
}

// HasAccountNumbers returns a boolean if a field has been set.
func (o *Beneficiary) HasAccountNumbers() bool {
	if o != nil && o.AccountNumbers != nil {
		return true
	}

	return false
}

// SetAccountNumbers gets a reference to the given []string and assigns it to the AccountNumbers field.
func (o *Beneficiary) SetAccountNumbers(v []string) {
	o.AccountNumbers = &v
}

func (o Beneficiary) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.BeneficiaryPersons != nil {
		toSerialize["beneficiary_persons"] = o.BeneficiaryPersons
	}
	if o.AccountNumbers != nil {
		toSerialize["account_numbers"] = o.AccountNumbers
	}
	return json.Marshal(toSerialize)
}

type NullableBeneficiary struct {
	value *Beneficiary
	isSet bool
}

func (v NullableBeneficiary) Get() *Beneficiary {
	return v.value
}

func (v *NullableBeneficiary) Set(val *Beneficiary) {
	v.value = val
	v.isSet = true
}

func (v NullableBeneficiary) IsSet() bool {
	return v.isSet
}

func (v *NullableBeneficiary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBeneficiary(val *Beneficiary) *NullableBeneficiary {
	return &NullableBeneficiary{value: val, isSet: true}
}

func (v NullableBeneficiary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBeneficiary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


