/*
 * Bridge
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ivms101

import (
	"encoding/json"
)

// NationalIdentification struct for NationalIdentification
type NationalIdentification struct {
	NationalIdentifier *string `json:"national_identifier,omitempty"`
	NationalIdentifierType *string `json:"national_identifier_type,omitempty"`
	CountryOfIssue *string `json:"country_of_issue,omitempty"`
	RegistrationAuthority *string `json:"registration_authority,omitempty"`
}

// NewNationalIdentification instantiates a new NationalIdentification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNationalIdentification() *NationalIdentification {
	this := NationalIdentification{}
	return &this
}

// NewNationalIdentificationWithDefaults instantiates a new NationalIdentification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNationalIdentificationWithDefaults() *NationalIdentification {
	this := NationalIdentification{}
	return &this
}

// GetNationalIdentifier returns the NationalIdentifier field value if set, zero value otherwise.
func (o *NationalIdentification) GetNationalIdentifier() string {
	if o == nil || o.NationalIdentifier == nil {
		var ret string
		return ret
	}
	return *o.NationalIdentifier
}

// GetNationalIdentifierOk returns a tuple with the NationalIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NationalIdentification) GetNationalIdentifierOk() (*string, bool) {
	if o == nil || o.NationalIdentifier == nil {
		return nil, false
	}
	return o.NationalIdentifier, true
}

// HasNationalIdentifier returns a boolean if a field has been set.
func (o *NationalIdentification) HasNationalIdentifier() bool {
	if o != nil && o.NationalIdentifier != nil {
		return true
	}

	return false
}

// SetNationalIdentifier gets a reference to the given string and assigns it to the NationalIdentifier field.
func (o *NationalIdentification) SetNationalIdentifier(v string) {
	o.NationalIdentifier = &v
}

// GetNationalIdentifierType returns the NationalIdentifierType field value if set, zero value otherwise.
func (o *NationalIdentification) GetNationalIdentifierType() string {
	if o == nil || o.NationalIdentifierType == nil {
		var ret string
		return ret
	}
	return *o.NationalIdentifierType
}

// GetNationalIdentifierTypeOk returns a tuple with the NationalIdentifierType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NationalIdentification) GetNationalIdentifierTypeOk() (*string, bool) {
	if o == nil || o.NationalIdentifierType == nil {
		return nil, false
	}
	return o.NationalIdentifierType, true
}

// HasNationalIdentifierType returns a boolean if a field has been set.
func (o *NationalIdentification) HasNationalIdentifierType() bool {
	if o != nil && o.NationalIdentifierType != nil {
		return true
	}

	return false
}

// SetNationalIdentifierType gets a reference to the given string and assigns it to the NationalIdentifierType field.
func (o *NationalIdentification) SetNationalIdentifierType(v string) {
	o.NationalIdentifierType = &v
}

// GetCountryOfIssue returns the CountryOfIssue field value if set, zero value otherwise.
func (o *NationalIdentification) GetCountryOfIssue() string {
	if o == nil || o.CountryOfIssue == nil {
		var ret string
		return ret
	}
	return *o.CountryOfIssue
}

// GetCountryOfIssueOk returns a tuple with the CountryOfIssue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NationalIdentification) GetCountryOfIssueOk() (*string, bool) {
	if o == nil || o.CountryOfIssue == nil {
		return nil, false
	}
	return o.CountryOfIssue, true
}

// HasCountryOfIssue returns a boolean if a field has been set.
func (o *NationalIdentification) HasCountryOfIssue() bool {
	if o != nil && o.CountryOfIssue != nil {
		return true
	}

	return false
}

// SetCountryOfIssue gets a reference to the given string and assigns it to the CountryOfIssue field.
func (o *NationalIdentification) SetCountryOfIssue(v string) {
	o.CountryOfIssue = &v
}

// GetRegistrationAuthority returns the RegistrationAuthority field value if set, zero value otherwise.
func (o *NationalIdentification) GetRegistrationAuthority() string {
	if o == nil || o.RegistrationAuthority == nil {
		var ret string
		return ret
	}
	return *o.RegistrationAuthority
}

// GetRegistrationAuthorityOk returns a tuple with the RegistrationAuthority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NationalIdentification) GetRegistrationAuthorityOk() (*string, bool) {
	if o == nil || o.RegistrationAuthority == nil {
		return nil, false
	}
	return o.RegistrationAuthority, true
}

// HasRegistrationAuthority returns a boolean if a field has been set.
func (o *NationalIdentification) HasRegistrationAuthority() bool {
	if o != nil && o.RegistrationAuthority != nil {
		return true
	}

	return false
}

// SetRegistrationAuthority gets a reference to the given string and assigns it to the RegistrationAuthority field.
func (o *NationalIdentification) SetRegistrationAuthority(v string) {
	o.RegistrationAuthority = &v
}

func (o NationalIdentification) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.NationalIdentifier != nil {
		toSerialize["national_identifier"] = o.NationalIdentifier
	}
	if o.NationalIdentifierType != nil {
		toSerialize["national_identifier_type"] = o.NationalIdentifierType
	}
	if o.CountryOfIssue != nil {
		toSerialize["country_of_issue"] = o.CountryOfIssue
	}
	if o.RegistrationAuthority != nil {
		toSerialize["registration_authority"] = o.RegistrationAuthority
	}
	return json.Marshal(toSerialize)
}

type NullableNationalIdentification struct {
	value *NationalIdentification
	isSet bool
}

func (v NullableNationalIdentification) Get() *NationalIdentification {
	return v.value
}

func (v *NullableNationalIdentification) Set(val *NationalIdentification) {
	v.value = val
	v.isSet = true
}

func (v NullableNationalIdentification) IsSet() bool {
	return v.isSet
}

func (v *NullableNationalIdentification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNationalIdentification(val *NationalIdentification) *NullableNationalIdentification {
	return &NullableNationalIdentification{value: val, isSet: true}
}

func (v NullableNationalIdentification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNationalIdentification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


