name: Publish Golang package
on:
  push:
    branches:
      - master
    paths:
      - golang/config.json
      - golang/example.go
      - bridge_and_ivms.json
      - .github/workflows/publish-golang.yml

defaults:
  run:
    working-directory: golang

jobs:
  publish-golang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download OpenAPI codegen jar
        run: |
          wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.0.0-beta/openapi-generator-cli-5.0.0-beta.jar -O ../gen.jar
      
      - name: Generate Golang code
        run: |
          java -jar ../gen.jar \
            generate -i ../bridge_and_ivms.json \
            --global-property models,modelTests=false,modelDocs=false \
            -g go-experimental \
            -c ./config.json \
            -o ./src

      - name: Commit generated golang code
        run: |
          git config --global user.name 'tech-sygna'
          git config --global user.email 'sygna.tech@coolbitx.com'
          if [[ ! -z $(git status --short) ]]
          then
            git add .
            git commit -m "Commit new generated code to repository"
            git push
          else
            echo "Generated code not changed."
          fi
