name: Publish Ruby package
on:
  push:
    branches:
      - master
    paths:
      - ruby/*
      - bridge_and_ivms.json
      - .github/workflows/publish-ruby.yml

defaults:
  run:
    working-directory: ruby/generated

jobs:
  publish-ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download OpenAPI codegen jar
        run: |
          wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.0.0-beta/openapi-generator-cli-5.0.0-beta.jar -O ../gen.jar
      
      - name: Generate code
        run: |
          java -jar ../gen.jar \
            generate -i ../../bridge_and_ivms.json \
            -g ruby \
            -o . \
            -c ../config.json
          ls -al

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Publish Ruby gem
        env:
          RUBY_API_KEY: ${{secrets.RUBY_API_KEY}}
        run: |
          mkdir ~/.gem
          echo "---" > ~/.gem/credentials
          echo ":rubygems_api_key: $RUBY_API_KEY" >> ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
          cat ~/.gem/credentials
          gem build sygna-bridge-ivms-util.gemspec -o o.gem
          gem push o.gem